export const shortenLists = [
  {
    field: "shortenId",
    headerName: "Id",
    width: 250,
    disableColumnMenu: false,
    headerAlign: "center",
    align: "center",
    editable: false,
    headerClassName: "text-black font-semibold border",
    cellClassName: "text-slate-700 font-normal  border",
    renderHeader: (params) => <span className="ps-10">Id</span>,
  },

  {
    field: "originalUrl",
    headerName: "OriginalUrl",
    width: 300,
    editable: false,
    headerAlign: "center",
    disableColumnMenu: true,
    align: "center",
    headerClassName: "text-black font-semibold border",
    cellClassName: "text-slate-700 font-normal  border",
    renderHeader: (params) => <span className="ps-10">OriginalUrl</span>,
  },

  {
    field: "shortUrl",
    headerName: "ShortUrl",
    disableColumnMenu: true,
    width: 300,
    editable: false,
    headerAlign: "center",
    align: "center",
    headerClassName: "text-black font-semibold ",
    cellClassName: "text-slate-700 font-normal  ",
    renderHeader: (params) => <span>ShortUrl</span>,
  },
];
export const analytics = [
  {
    field: "shortenId",
    headerName: "Id",
    width: 150,
    headerAlign: "center",
    disableColumnMenu: false,
    align: "center",
    editable: false,
    headerClassName: "text-black font-semibold ",
    cellClassName: "text-slate-700 font-normal  ",
    renderHeader: (params) => <span className="ps-10">Id</span>,
  },
  {
    field: "username",
    headerName: "UserName",
    width: 170,
    disableColumnMenu: true,
    align: "center",
    editable: false,
    headerClassName: "text-black font-semibold border",
    cellClassName: "text-slate-700 font-normal  border",
    renderHeader: (params) => <span className="ps-10">UserName</span>,
  },
  {
    field: "role",
    headerName: "Role",
    width: 150,
    headerAlign: "center",
    align: "center",
    editable: false,
    disableColumnMenu: true,
    headerClassName: "text-black font-semibold border",
    cellClassName: "text-slate-700 font-normal  border",
    renderHeader: (params) => <span className="ps-10">Role</span>,
  },
  {
    field: "clickCount",
    headerName: "Click Count",
    width: 170,
    headerAlign: "center",
    align: "center",
    disableColumnMenu: true,
    editable: false,
    headerClassName: "text-black font-semibold border",
    cellClassName: "text-slate-700 font-normal  border",
    renderHeader: (params) => <span className="ps-10">Click Count</span>,
  },

  {
    field: "originalUrl",
    headerName: "OriginalUrl",
    width: 230,
    editable: false,

    headerAlign: "center",
    disableColumnMenu: true,
    align: "center",
    headerClassName: "text-black font-semibold border",
    cellClassName: "text-slate-700 font-normal  border",
    renderHeader: (params) => <span className="ps-10">OriginalUrl</span>,
  },

  {
    field: "shortUrl",
    headerName: "ShortUrl",
    width: 210,
    disableColumnMenu: true,
    editable: false,
    headerAlign: "center",
    align: "center",
    headerClassName: "text-black font-semibold  ",
    cellClassName: "text-slate-700 font-normal  ",
    renderHeader: (params) => <span>ShortUrl</span>,
  },
];
